### PR TITLE
Julia 0.7

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
Do we need one last 0.6-compatible release before merging this?

**Comment by abelsiqueira** [comment]
Yes, to support 0.6 in the transition. I'll do it.

**Comment by abelsiqueira** [comment]
Thanks

**Comment by abelsiqueira** [comment]
We can release v0.1.0 supporting 0.7 now too.

**Comment by dpo** [comment]
Yes. Thanks!

**Pull request merged**
