### PR TITLE
Tikz export for performance profiles

### PR DESCRIPTION
**Pull request by d-monnet**

### CODE REVIEW

**Comment by tmigot** [comment]
@d-monnet Can you rebase your branch to be up-to-date with main ? It would fix the conflict. Thanks!

**Comment by d-monnet** [comment]
> @d-monnet Can you rebase your branch to be up-to-date with main ? It would fix the conflict. Thanks!

Done, shouldn't be any more conflicts.

**Comment by dpo** [comment]
There are 20 commits in here, including two merge commits. Could you please start from a clean branch and add your new commit?

**Comment by dpo** [comment]
Have you seen https://github.com/JuliaTeX/TikzPictures.jl ?

**Pull request closed without merging**
