### PR TITLE
Add PGFPlotsX backend

### PR DESCRIPTION
**Pull request by geoffroyleconte**

### CODE REVIEW

**Review by tmigot — COMMENTED** [review]
Thanks for this new feature! Could you also add a test for this similar to https://github.com/JuliaSmoothOptimizers/BenchmarkProfiles.jl/blob/d65d86c6dc86e76d678483cff0f1075fee500409/test/runtests.jl#L23 ?

**Comment by geoffroyleconte** [comment]
> Thanks for this new feature! Could you also add a test for this similar to
> 
> https://github.com/JuliaSmoothOptimizers/BenchmarkProfiles.jl/blob/d65d86c6dc86e76d678483cff0f1075fee500409/test/runtests.jl#L23
> ?

That's not very convenient because it would require adding PGFPlotsX to the dependancies.

**Comment by tmigot** [comment]
It would only be in the test deps not the package. Same for UnicodePlots.

**Review by tmigot — APPROVED** [review]
Thanks!

**Comment by dpo** [comment]
Very nice! This has been on my list for a long time!

**Pull request merged**
